#!/bin/sh

B='74747400'  # blank
C='#74747422'  # clear ish
D='#747474'  # default
T='#747474'  # text
W='#ff0000bb'  # wrong
V='#747474'  # verifying

/usr/bin/i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$W        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 10              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A %d.%m.%Y" \
--keylayout 2         \

# --veriftext="Drinking verification can..."
#--wrongtext="Wrong Password."
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
